scaling_movements = {
    "HSPU": "HSPU: Elevated HSPU (Use a riser that allows +/- 5 Reps UB) > Box Pike Push-ups",
    "Strict HSPU": "Strict HSPU: Elevated Strict HSPU (Use a riser that allows +/- 5 Reps UB) > Box Pike Push-ups",
    "C2W HSPU": "C2W HSPU: Elevated C2W HSPU (Use a riser that allows +/- 5 Reps UB) > Box Pike Push-ups",
    "Freestanding HSPU": "Freestanding HSPU practice (video)",
    "Wall Walk": "Wall Walk: Half Wall Walks > Box Walk",
    "WW+C2W": "WW+C2W: Box Walk + Box Pike Push-ups",
    "HSW": "HSW (25ft = 7.62m): 30\" Walk to Wall Drill > 10 Wall Facing Plate Shoulder Taps > 2 Wall Walk",
    "Freestanding Handstand Hold": "Freestanding Handstand Hold > Single Leg Lift > Chest to Box > Stacked Plates",
    "Burpee Box Get Overs": "Burpee Box Get Overs @120/100cm > BBJO 75/60cm > BBJO 60/50cm",
    "BMU": "BMU: Banded BMU (Use a Band that allows +/- 5 Reps UB) > Strict C2B > Strict Pull-ups",
    "RMU": "RMU: Low Ring Banded Muscle ups + Strict/Jump Dip (Use a band that allows +/- 5 Reps UB)",
    "Strict RMU": "Strict RMU: Seated Banded Strict RMU",
    "Push-ups": "Push-ups: Knee Push-ups > Box Push-ups",
    "Ring Dips": "Ring Dips: Banded Ring Dips (Use a band that allows +/- 5 Reps UB)",
    "Pull-ups": "Pull-ups: Banded Strict Pull-up (Use a Band that allows +/- 5 Reps UB)",
    "C2B": "C2B: Pull-ups > Banded Strict Pull-up (Use a band that allows +/- 5 Reps UB)",
    "TTB": "TTB: Knee to Chest & Kick > One Leg TTB > Knee to Chests > Supinated TTB",
    "TTR": "TTR: Knee to Chest & Kick > One Leg TTR > Knee to Chests",
    "Strict Pull-ups": "Strict Pull-ups: Banded Strict Pull-up (Use a band that allows +/- 5 Reps UB)",
    "Pull-Overs": "Pull-Overs: Box Pullovers",
    "GHD Sit-ups": "GHD Sit-ups: GHD to Parallel > AB Mat Sit-ups",
    "V-ups": "V-ups Sit-ups: Tuck-ups",
    "Rope Climb Legless": "Rope Climb Legless: 1 Half Rope Climb Legless > 1 Rope Climb > 1 Half Rope Climb > 2 Laying to Stand Rope Climbs",
    "Rope Climb": "Rope Climb: 1 Half Rope Climb > 2 Laying to Stand Rope Climbs",
    "Pegboard": "Pegboard: Half Pegboard",
    "Pistols": "Pistols: Assisted Pistols > Skater Squats > Reverse Lunges",
    "DU": "DU: Same Number Single Unders",
    "SUCO": "SUCO: Double Unders > Single Unders",
    "DUCO": "DUCO > 2x SUCO > 1x Double Unders > 2x Single Unders",
    "Heavy Rope DU": "Heavy Rope DU > DU > Heavy Rope SU > SU (Same numbers)"
}
